id: A724455B6
base_file: fC4F9.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:36:36.075038
  last_modified_at: 2022-06-11 13:36:36.075058
