id: A724455B6
base_file: f0F81.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:36:36.072961
  last_modified_at: 2022-06-11 13:36:36.072968
